const result = [
  /* 2023 */
  {
    year: '2023',
    ap: [
      {
        order: 1,
        subject: 'AP Chemistry',
        heading: '100% students got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Lau'],
      },
      {
        order: 2,
        subject: 'AP Biology',
        heading: '100% students got Level 5 & 4',
        level5: 5,
        level4: 3,
        students_ICS: [
          'Kan',
          'Lau',
          'Lee',
          'Ngai',
          'Ngan',
          'Tsih',
          'Wong',
          'Wong',
        ],
      },
      {
        order: 3,
        subject: 'AP Physic 2',
        heading: '100% students got Level 5 & 4',
        level5: 1,
        level4: 1,
        students_ICS: ['Poon', 'Wong'],
      },
      {
        order: 4,
        subject: 'AP Physic C',
        heading: '100% students got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Ho'],
      },
      {
        order: 5,
        subject: 'AP Statistics',
        heading: '100% students got Level 5',
        level5: 3,
        level4: 0,
        students_ICS: ['Chan', 'Mok', 'Wong'],
      },
      {
        order: 6,
        subject: 'AP Calculus AB/BC',
        heading: '100% students got Level 5',
        level5: 6,
        level4: 0,
        students_ICS: [
          'Law',
          'Kan',
          'Wong',
          'Lau',
          'Ho',
          'Too(Shanghai Concordia)',
        ],
      },
    ],
  },

  /* 2022 */
  {
    year: '2022',
    ap: [
      {
        order: 1,
        subject: 'AP Chemistry',
        heading: 'Almost 80% students got Level 5 & 4',
        level5: 4,
        level4: 2,
        students_ICS: [
          'Chan',
          'Ngai',
          'Ngai',
          'Tam',
          'Tam',
          'Tong',
          'Wong',
          'Wu',
        ],
      },
      {
        order: 2,
        subject: 'AP Biology',
        heading: '100% students got Level 5 & 4',
        level5: 2,
        level4: 2,
        students_ICS: ['Lai', 'Law', 'Poon'],
        students_others: ['Kan(TAS)'],
      },
      {
        order: 3,
        subject: 'AP Statistics',
        heading: 'Over 80% students got Level 5',
        level5: 4,
        level4: 1,
        students_ICS: ['Li', 'Liu', 'Ngai', 'Poon', 'Tsih', 'Wu'],
      },
      {
        order: 4,
        subject: 'AP Calculus BC',
        heading: '100% students got Level 5',
        level5: 2,
        level4: 0,
        students_ICS: ['Tong', 'Wong'],
      },
      {
        order: 5,
        subject: 'AP Physics 1',
        heading: '100% students got Level 5',
        level5: 2,
        level4: 0,
        students_ICS: ['Kan', 'Wong'],
      },
    ],
  },
  /* 2021 */
  {
    year: '2021',
    ap: [
      {
        order: 1,
        subject: 'AP Biology',
        heading: 'Almost 90% students got Level 5',
        level5: 7,
        level4: 1,
        students_ICS: [
          'Chan',
          'Cheung',
          'Kee',
          'Kwan',
          'Leung',
          'Yeung',
          'Yeung',
        ],
      },
      {
        order: 2,
        subject: 'AP Chemistry',
        heading: 'Over 80% students got Level 5 & 4',
        level5: 4,
        level4: 2,
        students_ICS: ['Chan', 'Chan', 'Cheung', 'Law', 'Liu', 'Poon'],
      },
      {
        order: 3,
        subject: 'AP Calculus BC',
        heading: '100% students got Level 5',
        level5: 3,
        level4: 0,
        students_ICS: ['Leung', 'Li', 'Yeung'],
      },
      {
        order: 4,
        subject: 'AP Physics 2',
        heading: '100% student got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Kwan'],
      },
      {
        order: 5,
        subject: 'AP Statistics',
        heading: 'Over 80% students got Level 5',
        level5: 5,
        level4: 0,
        students_ICS: ['Chan', 'Kee', 'Law', 'Sung', 'Tong', 'Yeung'],
      },
      {
        order: 6,
        subject: 'AP Calculus AB',
        heading: '100% students got Level 5',
        level5: 2,
        level4: 0,
        students_ICS: ['Tang', 'Tran'],
      },
      {
        order: 7,
        subject: 'AP Physics 1',
        heading: '100% student got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Chan'],
      },
      {
        order: 8,
        subject: 'AP Physics C',
        heading: '100% student got Level 5',
        level5: 3,
        level4: 0,
        students_ICS: ['Kwan', 'Ma', 'Sung'],
      },
    ],
  },
  /* 2020 */
  {
    year: '2020',
    ap: [
      {
        order: 1,
        subject: 'AP Chemistry',
        heading: 'Over 70% students got Level 5',
        level5: 5,
        level4: 2,
        students_ICS: ['Guo', 'Kee', 'Kwan', 'Li', 'Mak', 'Sung', 'Yeung'],
      },
      {
        order: 2,
        subject: 'AP Biology',
        heading: '100% student got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Chan(ICS)'],
      },
      {
        order: 3,
        subject: 'AP Statistic',
        heading: 'Over 83% students got Level 5',
        level5: 3,
        level4: 1,
        students_ICS: ['Chan', 'Guo', 'Li', 'Tang', 'Tran', 'Yeung'],
      },
      {
        order: 4,
        subject: 'AP Physics',
        heading: '80% students got Level 5',
        level5: 4,
        level4: 1,
        students_ICS: ['Kwan', 'Ma', 'Sung', 'Wong', 'Yeung'],
      },
      {
        order: 5,
        subject: 'AP Calculus AB',
        heading: '100% student got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Wu'],
      },
      {
        order: 6,
        subject: 'AP Calculus BC',
        heading: '100% students got Level 5',
        level5: 6,
        level4: 0,
        students_ICS: ['Chan', 'Kee', 'Kwan', 'Ma', 'Sung', 'Wong'],
      },
    ],
  },
  /* 2019 */
  {
    year: '2019',
    ap: [
      {
        order: 1,
        subject: 'AP Chemistry',
        heading: 'ALL got 4 and above',
        level5: 1,
        level4: 1,
        students_ICS: ['Chan', 'Leung'],
      },
      {
        order: 2,
        subject: 'AP Biology',
        heading: 'ALL got 4 and above',
        level5: 2,
        level4: 4,
        students_ICS: ['Guo', 'Lee', 'Leung', 'Lo', 'Mak', 'Ngai'],
      },
      {
        order: 3,
        subject: 'AP Statistic',
        heading: 'ALL got 4 and above',
        level5: 4,
        level4: 2,
        students_ICS: ['Chan', 'Chung', 'Lee', 'Kwan', 'Ma', 'Mak'],
      },
      {
        order: 4,
        subject: 'AP Calculus AB',
        heading: '100% students got Level 5',
        level5: 1,
        level4: 0,
        students_ICS: ['Lo'],
      },
    ],
    sat: [
      {
        order: 5,
        subject: 'SAT Biology E',
        heading: 'ALL got 720 and above',
        level5: '760: 1 student; 720:1 student',
        level4: 0,
        students_ICS: ['Leung', 'Ngai'],
      },
      {
        order: 6,
        subject: 'SAT Biology M',
        heading: '100% students full score',
        level5: '800: 1 student',
        level4: 0,
        students_ICS: ['Mak'],
      },
      {
        order: 7,
        subject: 'SAT Chemistry',
        heading: 'ALL got 740 and above',
        level5: '740: 1 student',
        level4: 0,
        students_ICS: ['Leung'],
      },
    ],
  },
];

//adding a function
//using forEach, each students_ICS + (ICS)

export { result };
